### ISSUE TITLE
ERROR: Unexpected segmentation fault encountered in worker.

### ISSUE THREAD

**Issue by chenbolinstudent** [STVIR/pysot#140]
ERROR: Unexpected segmentation fault encountered in worker.
Traceback (most recent call last):
  File "../../tools/train.py", line 332, in <module>
    main()
  File "../../tools/train.py", line 327, in main
    train(train_loader, dist_model, optimizer, lr_scheduler, tb_writer)
  File "../../tools/train.py", line 179, in train
    for idx, data in enumerate(train_loader):
  File "/home/public/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 330, in __next__
    idx, batch = self._get_batch()
  File "/home/public/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 309, in _get_batch
    return self.data_queue.get()
  File "/home/public/anaconda3/lib/python3.6/queue.py", line 164, in get
    self.not_empty.wait()
  File "/home/public/anaconda3/lib/python3.6/threading.py", line 295, in wait
    waiter.acquire()
  File "/home/public/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 227, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 1657) is killed by signal: Segmentation fault. Details are lost due to multiprocessing. Rerunning with num_workers=0 may give better error trace.

**Comment by xi-mao** [comment]
你解决了这个问题吗？我在docker中运行会报这个错

**Comment by yc-zc** [comment]
What's your size of memory?

**Comment by yc-zc** [comment]
What's your size of memory?


> 你解决了这个问题吗？我在docker中运行会报这个错

试着把内存开大一些

**Comment by yc-zc** [comment]
Since no further question is asked, I'm closing it for now.
Please reopen it or create a new issue if you have further question.
