### ISSUE TITLE
KeyError: 'Non-existent config key: BACKBONE.LAYERS'

### ISSUE THREAD

**Issue by yang-ai-min** [STVIR/pysot#178]
(pysot) MYPC@MYPC-XX-XXXX:~/pysot$ python tools/demo.py \
>     --config experiments/siamrpn_r50_l234_dwxcorr/config.yaml \
>     --snapshot experiments/siamrpn_r50_l234_dwxcorr/model.pth \
>     --video demo/bag.avi
Traceback (most recent call last):
  File "tools/demo.py", line 109, in <module>
    main()
  File "tools/demo.py", line 60, in main
    cfg.merge_from_file(args.config)
  File "/home/yx/anaconda3/envs/pysot/lib/python3.7/site-packages/yacs/config.py", line 213, in merge_from_file
    self.merge_from_other_cfg(cfg)
  File "/home/yx/anaconda3/envs/pysot/lib/python3.7/site-packages/yacs/config.py", line 217, in merge_from_other_cfg
    _merge_a_into_b(cfg_other, self, self, [])
  File "/home/yx/anaconda3/envs/pysot/lib/python3.7/site-packages/yacs/config.py", line 460, in _merge_a_into_b
    _merge_a_into_b(v, b[k], root, key_list + [k])
  File "/home/yx/anaconda3/envs/pysot/lib/python3.7/site-packages/yacs/config.py", line 473, in _merge_a_into_b
    raise KeyError("Non-existent config key: {}".forma

I install pysot twice. First I follow the guide in install.md. I activate conda environments and pip packages. Second time I bash the install.sh. I also try to pip yacs again in the pysot environment, but still failed to solve this problem.

**Comment by winer1997** [comment]
Are you replacing all the things in folder “experiments” with something from BaiduYun or Google Drive provided by author? All files called "config.yaml" in this folder have been modified , but author did not update it in the network disk , using the new version in this project. 
so, just add model filles and try it again.

**Comment by yang-ai-min** [comment]
> Are you replacing all the things in folder “experiments” with something from BaiduYun or Google Drive provided by author? All files called "config.yaml" in this folder have been modified , but author did not update it in the network disk , using the new version in this project.
> so, just add model filles and try it again.
