### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by daiwc** [STVIR/pysot#187]
The command that i used is "CUDA_VISIBLE_DEVICES=0,1 python -m torch.distributed.launch --nproc_per_node=2   ../../tools/train.py --cfg config.yaml"
  and after load model and wait a long time.some bugs happen.
[2019-09-24 14:19:51,955-rk0-distributed.py<reduce_gradients>#131] gradients method is sum
Traceback (most recent call last):
  File "../../tools/train.py", line 324, in <module>
    main()
  File "../../tools/train.py", line 319, in main
    train(train_loader, dist_model, optimizer, lr_scheduler, tb_writer)
  File "../../tools/train.py", line 180, in train
    for idx, data in enumerate(train_loader):
  File "/home/xxx/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 336, in __next__
    return self._process_next_batch(batch)
  File "/home/xxx/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 357, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
AttributeError: Traceback (most recent call last):
  File "/home/xxx/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 106, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/xxx/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 106, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/xxx/pysot-master/pysot/datasets/dataset.py", line 253, in __getitem__
    template_box = self._get_bbox(template_image, template[1])
  File "/home/xx/pysot-master/pysot/datasets/dataset.py", line 214, in _get_bbox
    imh, imw = image.shape[:2]
AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by hqabcxyxz** [comment]
It seems that  your image is load failed...

**Comment by adrift00** [comment]
Your image path should not contain chinese characters, because cv2.imread() don't support it.

**Comment by daiwc** [comment]
> Your image path should not contain chinese characters, because cv2.imread() don't support it.

I have make sure that my image path don't have chinese characters.

**Comment by adrift00** [comment]
Maybe you need to check the images needed is prepared already.

**Comment by renlicheng** [comment]
@daiwc  大哥问题解决了吗。我遇到了相同的问题，求救啊！！！

**Comment by yc-zc** [comment]
The image was not properly read, please ensure the images are read properly.
Since no further question is asked, I'm closing it for now.
Please reopen it or create a new issue if you have further question.
