### ISSUE TITLE
Test tracker and TypeError: __init__() got an unexpected keyword argument 'new_allowed'

### ISSUE THREAD

**Issue by sxs11** [STVIR/pysot#244]
I just want to run the part of test tracker, using the model.pth from the pysot model zoo.
But the error is :
/data1/pysot/experiments/siamrpn_r50_l234_dwxcorr# python -u ../../tools/test.py --snapshot model.pth --dataset VOT2018 --config config.yaml
Traceback (most recent call last):
  File "../../tools/test.py", line 15, in <module>
    from pysot.core.config import cfg
  File "/data1/pysot/pysot/core/config.py", line 86, in <module>
    __C.TRAIN.LR.KWARGS = CN(new_allowed=True)
TypeError: \_\_init\_\_() got an unexpected keyword argument 'new_allowed'

I use pytorch1.1.0, python3.7 and a single GPU.

Does anyone can give some advice? thanks

**Comment by sxs11** [comment]
I figured it out. The version of yacs is wrong. mine is 0.1.4, and has no new_allowed.
Now I use version 0.1.6, and the error disappears
