### ISSUE TITLE
有人知道baidu网盘下来的youtube-bb文件怎么用吗？测试过，感觉是youbube-bb数据集的问题。

### ISSUE THREAD

**Issue by cappuccino19** [STVIR/pysot#246]
直接下载youbube-bb数据库，提示已经移除。

**Comment by cappuccino19** [comment]
训练时出现如下错误。
Traceback (most recent call last):
File "../../tools/train.py", line 319, in 
main()
File "../../tools/train.py", line 314, in main
train(train_loader, dist_model, optimizer, lr_scheduler, tb_writer)
File "../../tools/train.py", line 176, in train
for idx, data in enumerate(train_loader):
File "/home/gao/anaconda3/envs/pysot/lib/python3.7/site-packages/torch/utils/d

ata/dataloader.py", line 336, in next
return self._process_next_batch(batch)
File "/home/gao/anaconda3/envs/pysot/lib/python3.7/site-packages/torch/utils/d

ata/dataloader.py", line 357, in _process_next_batch
raise batch.exc_type(batch.exc_msg)
AttributeError: Traceback (most recent call last):
File "/home/gao/anaconda3/envs/pysot/lib/python3.7/site-packages/torch/utils/d

ata/dataloader.py", line 106, in _worker_loop
samples = collate_fn([dataset[i] for i in batch_indices])
File "/home/gao/anaconda3/envs/pysot/lib/python3.7/site-packages/torch/utils/d

ata/dataloader.py", line 106, in 
samples = collate_fn([dataset[i] for i in batch_indices])
File "/media/gao/pysot-master/pysot/datasets/dataset.py", line 253, in __getit

em__
template_box = self._get_bbox(template_image, template[1])
File "/media/gao/pysot-master/pysot/datasets/dataset.py", line 214, in _get_bb

ox
imh, imw = image.shape[:2]
AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by SteveTsg** [comment]
数据集是有问题，我在__getitem__的时候跳过了这些有问题的图

**Comment by cappuccino19** [comment]
不好意思，如何跳过的呢？ 困扰我好久了。多谢。
[2020-01-07 17:47:14,407-rk0-distributed.py<reduce_gradients>#131] gradients met

hod is sum
Traceback (most recent call last):
  File "../../tools/train.py", line 317, in <module>
    main()
  File "../../tools/train.py", line 312, in main
    train(train_loader, dist_model, optimizer, lr_scheduler, tb_writer)
  File "../../tools/train.py", line 175, in train
    for idx, data in enumerate(train_loader):
  File "/home/gao/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloa

der.py", line 336, in __next__
    return self._process_next_batch(batch)
  File "/home/gao/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloa

der.py", line 357, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
AttributeError: Traceback (most recent call last):
  File "/home/gao/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloa

der.py", line 106, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/gao/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloa

der.py", line 106, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/media/gao/pysot-master/pysot/datasets/dataset.py", line 254, in __getit

em__
    search_box = self._get_bbox(search_image, search[1])
  File "/media/gao/pysot-master/pysot/datasets/dataset.py", line 214, in _get_bb

ox
    imh, imw = image.shape[:2]
AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by SteveTsg** [comment]
我是先读图，有问题就index++再读，直到图片没问题就下一个啊

**Comment by cappuccino19** [comment]
您好，我是初学者，方便共享一下你的处理方式吗？多谢。40181482@qq.com

**Comment by way790110** [comment]
@cappuccino19 你有微信嗎?我們這邊有一些人也在討論pysot 可以一起討論

**Comment by name-heyu** [comment]
> 我是先读图，有问题就index++再读，直到图片没问题就下一个啊

请问能麻烦分享一下youtube-bb文件的链接吗？pysot里提供的失效了，谢谢了

**Comment by SteveTsg** [comment]
> > 我是先读图，有问题就index++再读，直到图片没问题就下一个啊
> 
> 请问能麻烦分享一下youtube-bb文件的链接吗？pysot里提供的失效了，谢谢了

YOUTUBEBB (New link for cropped data, BaiduYun, extract code: 6dd5. NOTE: Data in old link is not correct. Please use cropped data in this new link.)这个链接失效了？
https://pan.baidu.com/s/1vC4cRktPl27CFWYqR7194Q 提取码:9tjo，试一下这个

**Comment by name-heyu** [comment]
收到了，非常谢谢你

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: SteveTsg <notifications@github.com&gt;
发送时间: 2020年3月18日 16:39
收件人: STVIR/pysot <pysot@noreply.github.com&gt;
抄送: name-heyu <178837059@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[STVIR/pysot] 有人知道baidu网盘下来的youtube-bb文件怎么用吗？测试过，感觉是youbube-bb数据集的问题。 (#246)





   
我是先读图，有问题就index++再读，直到图片没问题就下一个啊
  
请问能麻烦分享一下youtube-bb文件的链接吗？pysot里提供的失效了，谢谢了
  
YOUTUBEBB (New link for cropped data, BaiduYun, extract code: 6dd5. NOTE: Data in old link is not correct. Please use cropped data in this new link.)这个链接失效了？
 https://pan.baidu.com/s/1vC4cRktPl27CFWYqR7194Q&nbsp;提取码:9tjo，试一下这个

**Comment by way790110** [comment]
此链接分享内容可能因为涉及侵权、色情、反动、低俗等信息，无法访问！
😢 😢 😢

**Comment by SteveTsg** [comment]
> 此链接分享内容可能因为涉及侵权、色情、反动、低俗等信息，无法访问！
> 😢 😢 😢

那就没办法了，要不自己去下载ytbb再自己preprocess？

**Comment by QuarK30** [comment]
> 收到了，非常谢谢你 发自我的iPhone
> […](#)
could you share your baidu link?

**Comment by u19900101** [comment]
> @cappuccino19 你有微信嗎?我們這邊有一些人也在討論pysot 可以一起討論
大佬求带一下我的微信17766901832

**Comment by zyc-ai** [comment]
#302

**Comment by Jee-King** [comment]
@cappuccino19 @u19900101 @way790110  能拉进微信群吗，我微信 18018981838

**Comment by EEEEEREN** [comment]
我也是出这个错，其他3个数据集就没问题，加载到ytb bb这个数据集就AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by swan2015** [comment]
哪位有youtube__bb的baidu云链接，自己下的快吐了，十分感谢

**Comment by Zhangming001** [comment]
> 哪位有youtube__bb的baidu云链接，自己下的快吐了，十分感谢

你找到百度云链接吗，
