### ISSUE TITLE
Dataloader error

### ISSUE THREAD

**Issue by chun-chun123** [STVIR/pysot#256]
![Image 74](https://user-images.githubusercontent.com/56161480/70488837-e1470a00-1b34-11ea-8455-16bdc9f9747a.png)

Traceback (most recent call last):
  File "../../tools/train.py", line 319, in <module>
    main()
  File "../../tools/train.py", line 314, in main
    train(train_loader, dist_model, optimizer, lr_scheduler, tb_writer)
  File "../../tools/train.py", line 176, in train
    for idx, data in enumerate(train_loader):
  File "/home/shichunze/anaconda3/envs/pysot/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 330, in __next__
    idx, batch = self._get_batch()
  File "/home/shichunze/anaconda3/envs/pysot/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 309, in _get_batch
    return self.data_queue.get()
  File "/home/shichunze/anaconda3/envs/pysot/lib/python3.7/queue.py", line 170, in get
    self.not_empty.wait()
  File "/home/shichunze/anaconda3/envs/pysot/lib/python3.7/threading.py", line 296, in wait
    waiter.acquire()
  File "/home/shichunze/anaconda3/envs/pysot/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 227, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 80064) exited unexpectedly with exit code 1. Details are lost due to multiprocessing. Rerunning with num_workers=0 may give better error trace.

Could someone tell me how to solve this?

**Comment by yc-zc** [comment]
Could you provide more details?

**Comment by chun-chun123** [comment]
Thanks for your attention.I have solved this problem,but meet a new one.
When I run 'train.py' with 3 GPUs,it was stuck after loading model.But there is no problem when I run with only one.
Could you please tell me why?

**Comment by yc-zc** [comment]
> Thanks for your attention.I have solved this problem,but meet a new one.
> When I run 'train.py' with 3 GPUs,it was stuck after loading model.But there is no problem when I run with only one.
> Could you please tell me why?

Sorry for our late reply. 
Could you please open a new issue in regards to your new issue?
Since the current issue has been resolved, I'm closing it for now.
