### ISSUE TITLE
Shape Error in Training

### ISSUE THREAD

**Issue by johko** [STVIR/pysot#35]
Hi,
when running the training for siamrpn_alex_dwxcorr as described, I always run into an error that seems to be related to tensor shapes:

Traceback (most recent call last):
  File "../../tools/train.py", line 316, in <module>
    main()
  File "../../tools/train.py", line 311, in main
    train(train_loader, dist_model, optimizer, lr_scheduler, tb_writer)
  File "../../tools/train.py", line 211, in train
    outputs = model(data)
  File "/home/users/kob/mastera/pysot/venv/lib/python3.5/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/users/kob/mastera/pysot/pysot/utils/distributed.py", line 43, in forward
    return self.module(*args, **kwargs)
  File "/home/users/kob/mastera/pysot/venv/lib/python3.5/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/users/kob/mastera/pysot/pysot/models/model_builder.py", line 103, in forward
    loc_loss = weight_l1_loss(loc, label_loc, label_loc_weight)
  File "/home/users/kob/mastera/pysot/pysot/models/loss.py", line 33, in weight_l1_loss
    diff = (pred_loc - label_loc).abs()
RuntimeError: The size of tensor a (17) must match the size of tensor b (25) at non-singleton dimension 4

**Comment by StrangerZhang** [comment]
siamrpn_alex_dwxcorr is used for inference
your should run the train.py in siamrpn_r50_l234_dwxcorr_8gpu folder, the config.yaml in this folder is used for training purpose

**Comment by johko** [comment]
Ah, I see, thank you. Works great now.
