### ISSUE TITLE
run demo 时出现 KeyError: 'Non-existent config key: BACKBONE.LAYERS'

### ISSUE THREAD

**Issue by justinluyao** [STVIR/pysot#353]
我下载好model 放入experiments以后 按照指令运行demo，出现以下错误

(pysot) G:\codes\pysot-master>python tools/demo.py --config experiments/siamrpn_mobilev2_l234_dwxcorr/config.yaml --snapshot experiments/siamrpn_mobilev2_l234_dwxcorr/model.pth --video demo/bag.avi
Traceback (most recent call last):
  File "tools/demo.py", line 113, in <module>
    main()
  File "tools/demo.py", line 64, in main
    cfg.merge_from_file(args.config)
  File "C:\Users\sunny\miniconda3\envs\pysot\lib\site-packages\yacs\config.py", line 213, in merge_from_file
    self.merge_from_other_cfg(cfg)
  File "C:\Users\sunny\miniconda3\envs\pysot\lib\site-packages\yacs\config.py", line 217, in merge_from_other_cfg
    _merge_a_into_b(cfg_other, self, self, [])
  File "C:\Users\sunny\miniconda3\envs\pysot\lib\site-packages\yacs\config.py", line 464, in _merge_a_into_b
    _merge_a_into_b(v, b[k], root, key_list + [k])
  File "C:\Users\sunny\miniconda3\envs\pysot\lib\site-packages\yacs\config.py", line 477, in _merge_a_into_b
    raise KeyError("Non-existent config key: {}".format(full_key))
KeyError: 'Non-existent config key: BACKBONE.LAYERS'

**Comment by ShihuaiXu** [comment]
我也遇到了同样的问题 请问兄弟你解决了吗

**Comment by justinluyao** [comment]
> 我也遇到了同样的问题 请问兄弟你解决了吗

初步估计是作者百度盘的config文件版本比较旧，我试试科学的去谷歌盘下载

**Comment by zyc-ai** [comment]
由于没有得到更进一步的提问，我现在将本议题关闭。
请创建一个新的议题，如果你有其他问题。
