### ISSUE TITLE
eval.py show_result have error

### ISSUE THREAD

**Issue by cherrysnowy** [STVIR/pysot#356]
|Tracker Name| Accuracy | Robustness | Lost Number |  EAO  |
------------------------------------------------------------
Traceback (most recent call last):
  File "../../tools/eval.py", line 146, in <module>
    main()
  File "../../tools/eval.py", line 131, in main
    show_video_level=args.show_video_level)
  File "/home/star/Documents/siamban/toolkit/evaluation/ar_benchmark.py", line 72, in show_result
    overlaps = list(itertools.chain(list(*ret['overlaps'].values())))
TypeError: list expected at most 1 arguments, got 60

**Comment by zyc-ai** [comment]
Could you please provide detailed steps to reproduce this issue?

**Comment by zyc-ai** [comment]
Since no further question is asked, I'm closing this issue for now. 
Please create a new issue should you have other questions.
