### ISSUE TITLE
No module named C

### ISSUE THREAD

**Issue by divastar** [STVIR/pysot#485]
I am using pycharm with
--nnodes=1 --node_rank=1 --nproc_per_node=1 --master_addr="109.64.173.149" C:\pysot-master\tools\train.py --cfg C:/pysot-master/experiments/siamrpn_r50_l234_dwxcorr/config.yaml

and getting 
C:\Python37\envs\pysot\python.exe "C:\Program Files\JetBrains\PyCharm 2017.3.3\helpers\pydev\pydevd.py" --module --multiproc --qt-support=auto --client 127.0.0.1 --port 5621 --file torch.distributed.launch --nnodes=1 --node_rank=1 --nproc_per_node=1 --master_addr=109.64.173.149 C:\pysot-master\tools\train.py --cfg C:/pysot-master/experiments/siamrpn_r50_l234_dwxcorr/config.yaml
pydev debugger: process 27924 is connecting

Connected to pydev debugger (build 173.4301.16)
pydev debugger: process 9668 is connecting

No module named C

Process finished with exit code 0

I cannot debug the code
Can you help?
What means No module named C

**Comment by divastar** [comment]
Now it gives:
C:\Python37\envs\pysot\python.exe -m torch.distributed.launch C:\pysot-master\tools\train.py --cfg C:/pysot-master/experiments/siamrpn_r50_l234_dwxcorr/config.yaml
Traceback (most recent call last):
  File "C:\pysot-master\pysot\utils\distributed.py", line 104, in dist_init
    rank, world_size = _dist_init()
  File "C:\pysot-master\pysot\utils\distributed.py", line 86, in _dist_init
    dist.init_process_group(backend='nccl')
  File "C:\Python37\envs\pysot\lib\site-packages\torch\distributed\distributed_c10d.py", line 421, in init_process_group
    init_method, rank, world_size, timeout=timeout
  File "C:\Python37\envs\pysot\lib\site-packages\torch\distributed\rendezvous.py", line 82, in rendezvous
    raise RuntimeError("No rendezvous handler for {}://".format(result.scheme))
RuntimeError: No rendezvous handler for env://

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\pysot-master\tools\train.py", line 325, in <module>
    main()
  File "C:\pysot-master\tools\train.py", line 265, in main
    rank, world_size = dist_init()
  File "C:\pysot-master\pysot\utils\distributed.py", line 111, in dist_init
    raise RuntimeError(*e.args)
RuntimeError: No rendezvous handler for env://
Traceback (most recent call last):
  File "C:\Python37\envs\pysot\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python37\envs\pysot\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python37\envs\pysot\lib\site-packages\torch\distributed\launch.py", line 260, in <module>
    main()
  File "C:\Python37\envs\pysot\lib\site-packages\torch\distributed\launch.py", line 256, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['C:\\Python37\\envs\\pysot\\python.exe', '-u', 'C:\\pysot-master\\tools\\train.py', '--local_rank=0', '--cfg', 'C:/pysot-master/experiments/siamrpn_r50_l234_dwxcorr/config.yaml']' returned non-zero exit status 1.

Process finished with exit code 1

Can someone help

**Comment by ZhiyuanChen** [comment]
The Windows support is in progress, it is encouraged to use this code with Linux. 
To use the code in Windows, you should remove all code related to DistributedDataParallel as it is not supported in Windows.
