### ISSUE TITLE
No module named 'pysot

### ISSUE THREAD

**Issue by chenbolinstudent** [STVIR/pysot#49]
I have 
export PYTHONPATH=/home/cbl/PycharmProjects/pysot-master/pysot:$PYTHONPATH

**Comment by chenbolinstudent** [comment]
where should I input :
export PYTHONPATH=/home/cbl/PycharmProjects/pysot-master/pysot:$PYTHONPATH  ?

**Comment by lb1100** [comment]
`export PYTHONPATH=/home/cbl/PycharmProjects/pysot-master:$PYTHONPATH`.

**Comment by chenbolinstudent** [comment]
but get another wrong
work/torch/lib/THD/process_group/General.cpp:17
[2019-06-14 15:22:32,914-rk0-distributed.py#112] Warning: use single process
[2019-06-14 15:22:32,914-rk0-train.py#260] init done
Traceback (most recent call last):
  File "../../tools/train.py", line 316, in <module>
    main()
  File "../../tools/train.py", line 265, in main
    os.makedirs(cfg.TRAIN.LOG_DIR)
  File "/home/public/anaconda3/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: './logs'

**Comment by lb1100** [comment]
`PermissionError: [Errno 13] Permission denied: './logs'`. Check your permission.

**Comment by chenbolinstudent** [comment]
it want to create the logs in the pysot-master ?

**Comment by chenbolinstudent** [comment]
Traceback (most recent call last):
  File "../../tools/train.py", line 24, in <module>
    from pysot.utils.lr_scheduler import build_lr_scheduler
ModuleNotFoundError: No module named 'pysot.utils.lr_scheduler'

**Comment by chenbolinstudent** [comment]
I watch the config.yaml, but donot find the  TRAIN.LOG_DIR in the  config.yaml
