### ISSUE TITLE
cfg.TRAIN.LOG_DIR

### ISSUE THREAD

**Issue by chenbolinstudent** [STVIR/pysot#53]
Traceback (most recent call last):
  File "../../tools/train.py", line 378, in <module>
    main()
  File "../../tools/train.py", line 327, in main
    os.makedirs(cfg.TRAIN.LOG_DIR)
  File "/home/public/anaconda3/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: './logs'

there is no cfg.TRAIN.LOG_DIR in the config.yaml
why os.makedirs(cfg.TRAIN.LOG_DIR)?

**Comment by lb1100** [comment]
It has default value in [config.py](https://github.com/STVIR/pysot/blob/master/pysot/core/config.py#L50). Just add a LOG_DIR into `config.yaml` if you wanna change it.
