### ISSUE TITLE
RuntimeError: cuda runtime error (59) :xxx

### ISSUE THREAD

**Issue by LearnByDoingXW** [STVIR/pysot#533]
When I run train.py on Ubuntu， I also meet this problem，The error message is as follows：

/opt/conda/conda-bld/pytorch_1535493744281/work/aten/src/THC/THCTensorIndex.cu:362: void indexSelectLargeIndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2, IndexIsMajor = true]: block: [4,0,0], thread: [0,0,0] Assertion srcIndex < srcSelectDimSize failed.

...
...
...
Traceback (most recent call last):
File "tools/train.py", line 346, in
main()
File "tools/train.py", line 336, in main
train(train_loader, dist_model, optimizer, lr_scheduler, tb_writer)
File "tools/train.py", line 217, in train
outputs = model(data)
File "/home/wy/anaconda3/envs/pysot/lib/python3.7/site-packages/torch/nn/modules/module.py", line 477, in call
result = self.forward(*input, **kwargs)
File "/media/wy/ee9c6cc3-4234-40f0-bc7c-fe7854a554d6/xiaowei/pysot/pysot/utils/distributed.py", line 43, in forward
return self.module(*args, **kwargs)
File "/home/wy/anaconda3/envs/pysot/lib/python3.7/site-packages/torch/nn/modules/module.py", line 477, in call
result = self.forward(*input, **kwargs)
File "/media/wy/ee9c6cc3-4234-40f0-bc7c-fe7854a554d6/xiaowei/pysot/pysot/models/model_builder.py", line 102, in forward
loc_loss = weight_l1_loss(loc, label_loc, label_loc_weight)
File "/media/wy/ee9c6cc3-4234-40f0-bc7c-fe7854a554d6/xiaowei/pysot/pysot/models/loss.py", line 34, in weight_l1_loss
diff = (pred_loc - label_loc).abs()
RuntimeError: The size of tensor a (17) must match the size of tensor b (25) at non-singleton dimension 4
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1535493744281/work/torch/lib/THD/base/data_channels/DataChannelNccl.cpp line=195 error=59 : device-side assert triggered
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
File "/home/wy/anaconda3/envs/pysot/lib/python3.7/site-packages/torch/distributed/init.py", line 41, in destroy_process_group
torch._C._dist_destroy_process_group()
RuntimeError: cuda runtime error (59) : device-side assert triggered at /opt/conda/conda-bld/pytorch_1535493744281/work/torch/lib/THD/base/data_channels/DataChannelNccl.cpp:195 at /opt/conda/conda-bld/pytorch_1535493744281/work/torch/lib/THD/process_group/General.cpp:26

If someone can help me, I will be very grateful!

**Comment by LearnByDoingXW** [comment]
报错的运行是根据siamrpn_alex_dwxcorr下的config.yaml   但我用siamrpn_r50_l234_dwxcorr下的配置文件时，不报错

**Comment by Scheaven** [comment]
> 报错的运行是根据siamrpn_alex_dwxcorr下的config.yaml 但我用siamrpn_r50_l234_dwxcorr下的配置文件时，不报错

?我看了两个配置文件，没有发现什么错误呀，为什么使用alex主干的不行？能否指导一下
