### ISSUE TITLE
TypeError: unsupported operand type(s) for *: 'int' and 'NoneType'

### ISSUE THREAD

**Issue by tang0704** [STVIR/pysot#55]
Thanks for your work.

I used the following command under ''/experiments/siammask_r50_l3/'':
```
CUDA_VISIBLE_DEVICES=0 # change your cuda visible devices here
python -m torch.distributed.launch --nproc_per_node=1 --master_port=2333 ../../tools/train.py --cfg config.yaml
```   
But I encountered an error when I trained siammask:
```
Traceback (most recent call last):
  File "../../tools/train.py", line 316, in <module>
    main()
  File "../../tools/train.py", line 311, in main
    train(train_loader, dist_model, optimizer, lr_scheduler, tb_writer)
  File "../../tools/train.py", line 211, in train
    outputs = model(data)
  File "/data/anaconda3/envs/tang0.4.1/lib/python3.7/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/anaconda3/envs/tang0.4.1/lib/python3.7/site-packages/pysot/utils/distributed.py", line 43, in forward
    return self.module(*args, **kwargs)
  File "/data/anaconda3/envs/tang0.4.1/lib/python3.7/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/anaconda3/envs/tang0.4.1/lib/python3.7/site-packages/pysot/models/model_builder.py", line 113, in forward
    outputs['total_loss'] += cfg.TRAIN.MASK_WEIGHT * mask_loss
TypeError: unsupported operand type(s) for *: 'int' and 'NoneType'
```

Could you please tell me how to run train.py correctly? 

Thank you very much!

**Comment by lb1100** [comment]
You can use [siamrpn_r50_l234_dwxcorr_8gpu](https://github.com/STVIR/pysot/tree/master/experiments/siamrpn_r50_l234_dwxcorr_8gpu) or [siamrpn_r50_l234_dwxcorr_16gpu](https://github.com/STVIR/pysot/tree/master/experiments/siamrpn_r50_l234_dwxcorr_16gpu)  to train SiamRPN++. SiamMask only support inference yet. Training code for SiamMask will be ready recently.

**Comment by tang0704** [comment]
Thanks for your reply.
I'll close this issue.
