### ISSUE TITLE
can't run test.py correctly.

### ISSUE THREAD

**Issue by lattetaki** [STVIR/pysot#588]
I tried several hours and checked almost all the issues, still cannot run the test.py. I fixed many times, there are always errors, the most common one is:

loading OTB100:   0%|                                           | 0/100 [00:00<?, ?it/s, Basketball][ WARN:0@3.945] global /io/opencv/modules/imgcodecs/src/loadsave.cpp (239) findDecoder imread_('/root/SiamRPNpp/pysot/experiments/siamrpn_r50_l234_dwxcorr/Basketball/img/0001.jpg'): can't open/read file: check file path/integrity
loading OTB100:   0%|                                           | 0/100 [00:00<?, ?it/s, Basketball]
Traceback (most recent call last):
  File "../../tools/test.py", line 226, in <module>
    main()
  File "../../tools/test.py", line 56, in main
    dataset = DatasetFactory.create_dataset(name=args.dataset,
  File "/root/SiamRPNpp/pysot/toolkit/datasets/__init__.py", line 24, in create_dataset
    dataset = OTBDataset(**kwargs)
  File "/root/SiamRPNpp/pysot/toolkit/datasets/otb.py", line 95, in __init__
    self.videos[video] = OTBVideo(video,
  File "/root/SiamRPNpp/pysot/toolkit/datasets/otb.py", line 26, in __init__
    super(OTBVideo, self).__init__(name, root, video_dir,
  File "/root/SiamRPNpp/pysot/toolkit/datasets/video.py", line 27, in __init__
    assert img is not None, self.img_names[0]
AssertionError: /root/SiamRPNpp/pysot/experiments/siamrpn_r50_l234_dwxcorr/Basketball/img/0001.jpg

I'm confused because according to the quick start, there should no other folders under the siamrpn_r50_l234_dwxcorr, especially it's like a dataset. My dataset has been put into testing_dataset. 

By the way, because of my NVIDIA turing GPU, I have to use CUDA 11.X and matched torch. Is this the problem? According to the error information,  I don't think so but nothing else to explain.

**Comment by lattetaki** [comment]
this issue has been solved. I put the datasets into ./experiments/siamrpnXXX/, then the test.py started to work. It's not same as tutorial.

**Comment by lattetaki** [comment]
this problem is same as #399
