### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by linlu-qiu** [STVIR/pysot#72]
I tried to train using DET and VID by following the instructions. But the following error raised: 
```
    main()
  File "../../tools/train.py", line 311, in main
    train(train_loader, dist_model, optimizer, lr_scheduler, tb_writer)
  File "../../tools/train.py", line 176, in train
    for idx, data in enumerate(train_loader):
  File "/anaconda3/envs/pysot/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 336, in __next__
    return self._process_next_batch(batch)
  File "/anaconda3/envs/pysot/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 357, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
AttributeError: Traceback (most recent call last):
  File "/anaconda3/envs/pysot/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 106, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/anaconda3/envs/pysot/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 106, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/github/pysot/pysot/datasets/dataset.py", line 253, in __getitem__
    template_box = self._get_bbox(template_image, template[1])
  File "/github/pysot/pysot/datasets/dataset.py", line 214, in _get_bbox
    imh, imw = image.shape[:2]
AttributeError: 'NoneType' object has no attribute 'shape'
```
Also encountering video is not available error when preparing YOUTUBEBB dataset. Any idea how to solve this issue? Thanks! 

Never mind. Close this issue.

**Comment by lb1100** [comment]
NoneType means image not exists. Check your image path.

**Comment by qiullina** [comment]
The problem is only for DET and VID. I can successfully generate all json. Right now in `training_dataset`, I have 

```
vid 
   - ILSVRC2015
   - crop511
   - train.json
   - val.json 
   - ...
det 
   - ILSVRC
   - crop511
   - train.json 
   - val.json
   - ...
``` 

Is this the correct structure?

**Comment by NWPUWRY** [comment]
maybe your path includes Chinese.
