### ISSUE TITLE
    # load config     cfg.merge_from_file(args.config)

### ISSUE THREAD

**Issue by zhuyabin** [STVIR/pysot#83]
(pysot) zhuyabin@cvpruser:~/pysot-master$ python -m pdb tools/demo.py --config experiments/siamrpn_r50_l234_dwxcorr/config.yaml --snapshot experiments/siamrpn_r50_l234_dwxcorr/model.pth --video demo/bag.avi
> /home/zhuyabin/pysot-master/tools/demo.py(1)<module>()
-> from __future__ import absolute_import
(Pdb) c
Traceback (most recent call last):
  File "/home/zhuyabin/anaconda3/envs/pysot/lib/python3.7/pdb.py", line 1701, in main
    pdb._runscript(mainpyfile)
  File "/home/zhuyabin/anaconda3/envs/pysot/lib/python3.7/pdb.py", line 1570, in _runscript
    self.run(statement)
  File "/home/zhuyabin/anaconda3/envs/pysot/lib/python3.7/bdb.py", line 585, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "/home/zhuyabin/pysot-master/tools/demo.py", line 1, in <module>
    from __future__ import absolute_import
  File "/home/zhuyabin/pysot-master/tools/demo.py", line 60, in main
    cfg.merge_from_file(args.config)
  File "/home/zhuyabin/anaconda3/envs/pysot/lib/python3.7/site-packages/yacs/config.py", line 213, in merge_from_file
    self.merge_from_other_cfg(cfg)
  File "/home/zhuyabin/anaconda3/envs/pysot/lib/python3.7/site-packages/yacs/config.py", line 217, in merge_from_other_cfg
    _merge_a_into_b(cfg_other, self, self, [])
  File "/home/zhuyabin/anaconda3/envs/pysot/lib/python3.7/site-packages/yacs/config.py", line 460, in _merge_a_into_b
    _merge_a_into_b(v, b[k], root, key_list + [k])
  File "/home/zhuyabin/anaconda3/envs/pysot/lib/python3.7/site-packages/yacs/config.py", line 473, in _merge_a_into_b
    raise KeyError("Non-existent config key: {}".format(full_key))
KeyError: 'Non-existent config key: BACKBONE.LAYERS'
Uncaught exception. Entering post mortem debugging
Running 'cont' or 'step' will restart the program

**Comment by zhuyabin** [comment]
raise KeyError("Non-existent config key: {}".format(full_key))
KeyError: 'Non-existent config key: BACKBONE.LAYERS'

**Comment by StrangerZhang** [comment]
Ues the config.yaml in our repo, we update the config.yaml file recently.

**Comment by zhuyabin** [comment]
I just downloaded this file today and put it in the designated location.

**Comment by StrangerZhang** [comment]
I think you use the old version of config.yaml which in the google drive. We don't update the the config.yaml file in the google drive.

**Comment by zhuyabin** [comment]
Thanks for your reply.
I use baidu cloud download the config.yaml. 

 
---Original---
